services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\LuigisBoxBundle\:
        resource: '../../../../src/LuigisBoxBundle/{Service,Factory}'

    Answear\LuigisBoxBundle\Service\ConfigProvider:
        arguments:
            $host: '%answear_luigis_box.host%'
            $publicKey: '%answear_luigis_box.publicKey%'
            $privateKey: '%answear_luigis_box.privateKey%'
            $connectionTimeout: '%answear_luigis_box.connectionTimeout%'
            $requestTimeout: '%answear_luigis_box.requestTimeout%'

