services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\LuigisBoxBundle\:
        resource: '../../../../src/LuigisBoxBundle/{Service,Factory}'

    Answear\LuigisBoxBundle\Service\ConfigProvider: ~

